### ISSUE TITLE
What documents to prepare ....

### ISSUE THREAD

**Issue by lizzieinvancouver** [alinazeng/Tree_Spotters#1]
From @alinazeng 

Tentative Table of Contents:
1. Project Background 

    where I gave a brief overview of the Tree Spotter project, provide links to resources, mention the methods and how data was collected.

2. General Context (geographical and climatic)

    where I provide the basic context of the arboretum's geography and climate, the demographic of volunteers involved, timeline, etc.
    will include a few maps (geography) and graphs (climate & demographic)

3. What we looked at

    Tree species that we looked at and how many individuals each (map & pie chart)
    Routes that we had and how many individuals each (map)

4. Findings and discussion

    means of species x phenophase (line plots followed by figure captions detailing how doy and phenophases were characterized)
    what plant individuals were more frequently observed than others (map & pie chart)
    what routes were covered more than others (map & pie chart, bar chart)

5. Discussion of accuracy

    exemplify several cases of data outliers
    compare tree spotter pheno means to peer-reviewed journals

6. Acknowledgment

    where we credit all the involved parties

7. Appendix 

    datasheets, tree route maps and other things

**Comment by lizzieinvancouver** [comment]
@alinazeng I think there are two main files we want:

1. An overview PDF we can include on the website (https://temporalecology.org/treespotters/)
2. A file to share with the current Tree Spotters that will help them see how they sample and help us decide if we should add or remove and individual trees or species.

For 1 (overview). I think we should include from your Table of Contents (ToC): Project Background, General Context (geographical and climatic), What we looked at (also ADD: how many observations overall, how many observations of each phenophase (across all trees), how many observations of each species and percent of the total observations on each route). Then for the 'Findings and discussion' I think perhaps just some graphs of leafout and climate each year @cchambe12 I think already has code for these? I think we do not need a discussion yet, but this overview should have your 6-7 (Acknowledgment and Appendix). 

For 2 (file for current Tree Spotters). I think we can skip some of the intro and focus on 3-4 (What we looked at, can copy what you come up with for the overview), Findings and discussion, Discussion of accuracy. Again, I would not worry about too much text -- just be sure to caption each figure and jot down some overall notes on what you have found and we can work out what we want to write from there.

Let me know if any of this doesn't make sense and thank you again!

**Comment by alinazeng** [comment]
@lizzieinvancouver  Dear Lizzie. It was awesome seeing you today.

Please see attached the document with the figures I showed you earlier. Please make comments about (1) what other plots you would like to see (2) which ones you think are not necessary (3) any improvement and adjustment you would like me to make

All the texts, colors, captions, and layout are subject to change. I will put together a presentable template and work on the text once hearing back from you about the figures. 

Thank you so so much! No rush~
[Document_for_Tree_Spotter_VeryRough_Figures.pdf](https://github.com/alinazeng/Tree_Spotters/files/6659285/Document_for_Tree_Spotter_VeryRough_Figures.pdf)

**Comment by lizzieinvancouver** [comment]
(1) Other plots:
- Some trends over time? I would leave out 2015 but can we do average leafout day both overall (average across ALL data) and by species (but do not show species with very little data) plotted against year? And similar plots for 'fruits' and 'colored leaves' if there is enough data? 
- Can we do a map of leafout day for each tree? Maybe either pick the year with the most data or average across all years?

(2) Which ones not necessary:
- We maybe do not need the map showing tree diameter (or at least could be a in a 'supplemental figures' section at the end. 
- Number of yes/no/unsure bagraphs without phenophase (first one). I would keep the info in the caption though and put it in the next figure (faceted by phenophase). 
- I think drop the number of Yes observations for each phenophase on each species (keep next graph which is total observations) 
- Since we have the routes and observation frequency map (pg 16), I don't think we need the previous route map (pg 6) 
- Skip the number of observations per route by tree number since I think it is confounded with species (sadly). 

(3) Any improvements
- Figure X. This boxplot gives us an idea how many observations on average individual Tree Spotters contributed each year. **Can you write the mean value above each year? I would also put this figure second after total observations figure.**

**Comment by alinazeng** [comment]
Thanks lizzie @lizzieinvancouver. Will incorporate your suggestions when I finalize the document :))

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver -- add code on how to map in ggplot with size and shade of circles

**Comment by lizzieinvancouver** [comment]
@alinazeng Here's some mapping code ... I got the underlying map from [here](https://www.naturalearthdata.com/downloads/110m-physical-vectors/110m-land/)

```
##
## get map shape file (see map_notes.R for details)
library("viridis")
library(rgdal)
wmap <- readOGR("..//..//..//general/maps/ne_110m_land", layer="ne_110m_land")
wmap.df <- fortify(wmap)
# adjust the theme
theme.tanmap <- list(theme(panel.grid.minor = element_blank(),
                        # panel.grid.major = element_blank(),
                        panel.background = element_rect(fill = "grey90",colour = NA),
                        # plot.background = element_rect(fill=NA),
                        axis.title.x = element_blank(),
                        axis.title.y = element_blank(),
                        plot.title = element_text(size=22),
                        legend.position = "left"))   
## plotting
 plotme <- ggplot() + 
        geom_polygon(dat=wmap.df, aes(long, lat, group=group), fill="grey80") +
        geom_point(data=dfnvarzaggmerge, 
                   aes(x=lonclim, y=latclim, size=nvarz, fill=percommvarzoutside), 
                   colour="black", pch=21) +
        scale_fill_viridis(alpha=0.4) +
        theme.tanmap

## option to write out plot to file
    pdf(paste("graphs/maps/percentoutside", climvar[i], ".pdf", sep=""), width=9, height=4)
    print(plotme)
    dev.off()
```
