### ISSUE TITLE
Compare results ...

### ISSUE THREAD

**Issue by alinazeng** [alinazeng/Tree_Spotters#2]
Hi Lizzie,

I replotted the means using data that isn't too "clean." Could you take a look at the two plots please? I cannot judge how profound the differences are (please ignore the witch hazel as something weird is going on; I will have to account for that one separately later)

Take your time! This is not urgent.
Thank you<3

### plot with clean data (about 4256 observations)
![plot_with_cleaned_data](https://user-images.githubusercontent.com/83845945/119904949-16e5db80-bf00-11eb-9f0d-71576e6119db.png)

### plot with unclean data (about 14842 observations)

![plot_with_semi-raw_data](https://user-images.githubusercontent.com/83845945/119904960-1c432600-bf00-11eb-89b3-2d7c1ac59c47.png)

**Comment by lizzieinvancouver** [comment]
@alinazeng On first look, they look pretty similar to me! I always assume that uncleaned data would be crazy weird (biologically impossible answers) but this looks okay ... could you possibly make the two plots side by side so it is easier for me to compare them more in depth?

**Comment by alinazeng** [comment]
@lizzieinvancouver  Dear Lizzie. Please let me know if the image below helps. I appreciate your patience. 

![Comparison_side_by_side](https://user-images.githubusercontent.com/83845945/120026696-4dc2fc80-bfa7-11eb-8cdf-b6c174085aef.jpg)



also if you would like some craziness XDD I overlayed the two plots using Photoshop to allow for easier (or harder) comparison. please don't look at it if it makes you dizzy.

ps (black n white lines are for the uncleaned data)

![IMG_8581](https://user-images.githubusercontent.com/83845945/120027035-bc07bf00-bfa7-11eb-8602-4b233d2f883f.PNG)

**Comment by lizzieinvancouver** [comment]
@alinazeng Thanks for your patience while I thought about this. 

I think overall the uncleaned looks pretty comparable to the cleaned. 

But! That's not a good enough review to decide to go with uncleaned. What would be good is to make plots of **each** event for **each** species (yes, a lot of plots!) for **each** of the 5%, 50% and 95% quantiles (command in R is `quantile` I think) plotting the value using the cleaned on the X axis and the uncleaned on the Y and plot the 1:1 line on it ( `abline(0,1)` ) so we can compare more directly. This means if you have 3 events and 5 species, you'd need 3*5*3 figures. 

Let me know if you need help with the coding!

And, I probably will ask you to then do this by year ... 

A bit of work I know! But I think it will help us answer this question.

**Comment by alinazeng** [comment]
Hi Lizzie @lizzieinvancouver  Thanks for the response. I am on it!

I have several questions:
1) could you please clarify what values I am plotting on the axes? I'm having trouble visualizing what the plot might look like. 
2) did you mean to say if I had 3 events and 5 species, there would be 3*5*3 figures :))) I am not sure how the number 353 came about haha. Also if I were to do this by year, then the number of plots will need to be multiplied by another 5 (at least for most species)
3) is there a resource I could look at to get a better sense of what I am doing? I am not so sure why we are splitting things into different quantiles.

Appreciate your enlightenment!!

**Comment by lizzieinvancouver** [comment]
@alinazeng Yes, doing it by year would be more, but we should not worry about that ... yet.

1. Good point, I was not thinking it through clearly. I think we probably should the quantiles for each tree ID. Then each plot will be a scatterplot with as many dots as individual trees that we have. For each event (for example, leafout) for each species, you want to extract the 5% and 50% and 95% quantiles for the cleaned dataset and the uncleaned. If your data are set up in long format (so you have a row of dates for each event, for example), then you will need to extract the 5% quantile of that date (doy) column.  Here's a coarse example -- assume my 'test' object is your set of dates for one event for one species on either the cleaned data:

```
> test <- rnorm(10, 50, 8)
> test
 [1] 55.34904 57.83460 44.49134 55.63310 54.77800 51.14420 48.85713 55.88892 45.69639 44.77475
> quantile(test, 0.05)
      5% 
44.61888 
```

Now do the same for the uncleaned data. And plot.

2. Whoops! It should be 3 x 5  x 3 (3 events and 5 species x 3 quantiles).
3.  We're using quantiles instead of minimum, max, and mean. 

If you could make me a subset of the data on the repo (and tell me where to find it) -- say for one species for one event -- I could write some sample code!

**Comment by alinazeng** [comment]
Yayyy! Thank you Lizzie. This is a lot clearer now. I will link you to a subset of data later today~

**Comment by alinazeng** [comment]
@lizzieinvancouver Hi lizzie. Please see if these two csvs can be used.

- [unclean subset](https://github.com/alinazeng/Tree_Spotters/blob/main/output/unclean_bb_leafout_data_for_lizzie.csv)
- [clean subset](https://github.com/alinazeng/Tree_Spotters/blob/main/output/clean_bb_leafout_data_for_lizzie.csv)

I included two phases (bb and leafout) just in case.

Thank you for your help!

**Comment by lizzieinvancouver** [comment]
@alinazeng Here's a chunk of code to explain what I was thinking ...


```
rm(list=ls()) 
options(stringsAsFactors = FALSE)

setwd("~/Desktop")

library(plyr)
library(dplyr)
library(ggplot2)
library(tidyr)

cl <- read.csv("clean_bb_leafout_data_for_lizzie.csv")
uncl <- read.csv("unclean_bb_leafout_data_for_lizzie.csv")

# Side note -- when coming up with names, best to do spaces or capitals, not both (e.g., Scientific_Names) and honestly simpler is sometimes better, I would go with "species' or "latbi" (for Latin binomial)

# get the summary we need for plotting ... 
datsummcl <-
      ddply(cl, c("Scientific_Names", "phase", "year", "id"),
          summarise,
          quant5 = quantile(doy, 0.05, na.rm=TRUE),
          quant50 = quantile(doy, 0.5, na.rm=TRUE),
          quant95 = quantile(doy, 0.95, na.rm=TRUE),
          )

datsummuncl <-
      ddply(uncl, c("Scientific_Names", "phase", "year", "id"),
          summarise,
          quant5 = quantile(doy, 0.05, na.rm=TRUE),
          quant50 = quantile(doy, 0.5, na.rm=TRUE),
          quant95 = quantile(doy, 0.95, na.rm=TRUE),
          )

# merge so we can plot what we want ...
dat <- merge(datsummcl, datsummuncl,
    by=c("Scientific_Names", "phase", "year", "id"),
    suffixes=c("clean", "unclean"), all.x=TRUE, all.y=TRUE)

# plot, but not sure the best option ...
# Here's all species and years for one phase ... 
ggplot(subset(dat, phase=="budburst"),
    aes(quant5clean, quant5unclean, group=year, color=year)) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) + 
    facet_wrap(Scientific_Names~., scales="free")

# Here's one species so can see data better, for one phase ... 
ggplot(subset(dat, phase=="budburst" & Scientific_Names=="Acer rubrum"),
    aes(quant5clean, quant5unclean)) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) + 
    facet_wrap(year~., scales="free")

# Here's all species and years, but the other way, for one phase ... 
ggplot(subset(dat, phase=="budburst"),
    aes(quant5clean, quant5unclean, color=Scientific_Names)) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) + 
    facet_wrap(year~., scales="free")

# hmm, we should check why 2015 and 2018 have such high y axis values

```

**Comment by lizzieinvancouver** [comment]
I think maybe the first ggplot option is good, but see what you think. 

One downside of this is that it will drop all the cases where we have only one observation of the cleaned data (and so cannot calculate a quantile) but keep all the uncleaned ... so we should definitely also do a version of this code where we compare values by YEAR (basically in the ddply summarise command, drop "id"). 

Let me know if this helps!

**Comment by alinazeng** [comment]
Dear Lizzie @lizzieinvancouver,

Appreciate your guidance! I tried out your code and they work well. I also compared the values by dropping "id" when doing ddply summarize. 

Regarding why 2015 and 2018 unclean data is unusually high, I looked at the raw data and found a few outliers. Will update you after I made plots for other phases and see if this issue continues.

Both option 1 and 3 seem good to me and I don't mind making both versions. I will work on the plots tomorrow. 

Could you spare some time to meet this Friday or early next week? I have the frequency and other things ready and would love to chat before I start making the document. 

Thank you again!

**Comment by lizzieinvancouver** [comment]
@alinazeng Great work! It would be great to check if the outliers you found are being removed by the 'cleaning' -- if they're not it suggests moreso we might need a better way to clean.

I'll send you an email about scheduling.

**Comment by lizzieinvancouver** [comment]
@alinazeng We should definitely chat before you put time into the document -- I suggest we both agree on figures first.

**Comment by alinazeng** [comment]
@lizzieinvancouver  

Hi Lizzie. I have uploaded all the plots here:
https://github.com/alinazeng/Tree_Spotters/tree/main/output/plots/June_9_lots_of_plots_LizziePleaseSeeHere

Lemme know if the naming system does not make sense for you and I thank you for your time thinking about this. The raw data I used to make the plots can be found here: 

[clean](https://github.com/alinazeng/Tree_Spotters/blob/main/output/clean_raw_data_June_9.csv)
[unclean](https://github.com/alinazeng/Tree_Spotters/blob/main/output/unclean_raw_data_June_9.csv)

There is no rush! I will get started on the local adaption project in the meantime.

**Comment by lizzieinvancouver** [comment]
@alinazeng Thank you! Now I could use your help to understand a little why certain things are happening ... 

To start, I am looking at option1_with_id/option1_budburst_5.png -- in the top left (Acer rubrum) there are two dots towards the bottom. These are two trees where the uncleaned data suggest budburst around day 60 and the cleaned suggest budburst at roughly day 105 and 120. Could you tell me what tree IDs these are? If it's not too much data underlying each of those points could you paste the data (cleaned then uncleaned) into the issue for me to look at? (If it's a lot of data then I can just look at it in R myself.)

Thanks!

**Comment by alinazeng** [comment]
@lizzieinvancouver  Hi Lizzie. Sure thing. The two outliers' IDs are 166764 and 166765.

Please see the data subsets behind those points below:

[cleaned](https://github.com/alinazeng/Tree_Spotters/blob/main/output/aceroutliers_cl_June24.csv)
[uncleaned ](https://github.com/alinazeng/Tree_Spotters/blob/main/output/aceroutliers_uncl_June24.csv)

Thank you and see you tomorrow!
