### ISSUE TITLE
Accuracy discussion

### ISSUE THREAD

**Issue by alinazeng** [alinazeng/Tree_Spotters#4]
Hi Lizzie @lizzieinvancouver 

Here is the issue for how accurate the tree spotters' observations are. Please let me know how we could approach this.

I could explore ways to display the outlier doys, but this would be species-specific and year-specific 

Let me know what you think. thank you!

**Comment by lizzieinvancouver** [comment]
@alinazeng Okay, I thought about this and I don't think we can do anything about accuracy per se. Accuracy requires us to know the true value, and we just don't.

But we could give some precision metrics (how similar measurements are to one another). I think perhaps this could just be the % of observations for each phenophase (and each phenophase x species) that we keep after cleaning. What do you think of that?

**Comment by alinazeng** [comment]
hi lizzie. Sounds good. I will talk about precision.

By the way, do you have a png (or any format really) of the logo of Tree Spotters (see picture attached)

![Screenshot (134)](https://user-images.githubusercontent.com/83845945/128073953-fdef2628-823a-4658-b916-5c9767b6de1e.png)

Could I have it please?

Also, could you write me a list of parties involved that I should give credit to in the Acknowledgement section?

Thank you so much!
